x-deepstream-service: &deepstream-service
  image: huyquang/deepstream-app:8.0
  working_dir: /project
  command: python3 -u main.py
  restart: always
  network_mode: host
  volumes:
    - ./:/project
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ["0"]
            capabilities: [ gpu ]
  environment:
    - TZ=Asia/Ho_Chi_Minh
    - SERVER_ID=19

services:
  tg:
    <<: *deepstream-service
    container_name: tg
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SERVER_ID=10
      - AREA_CODE=HO_NKKN_TANG_G

  sacombank-camera-status:
    image: huyquang/deepstream-app:8.0
    working_dir: /project
    command: python3 -u check_camera_on_off.py
    restart: always
    network_mode: host
    volumes:
      - ./:/project
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SERVER_ID=10

  t1:
    <<: *deepstream-service
    container_name: t1
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SERVER_ID=10
      - AREA_CODE=HO_NKKN_TANG_1



  t2:
    <<: *deepstream-service
    container_name: t2
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SERVER_ID=10
      - AREA_CODE=HO_NKKN_TANG_2


  t3:
    <<: *deepstream-service
    container_name: t3
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SERVER_ID=10
      - AREA_CODE=HO_NKKN_TANG_3

  t4:
    <<: *deepstream-service
    container_name: t4
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SERVER_ID=10
      - AREA_CODE=HO_NKKN_TANG_4


  t5:
    <<: *deepstream-service
    container_name: t5
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SERVER_ID=10
      - AREA_CODE=HO_NKKN_TANG_5

  t6:
    <<: *deepstream-service
    container_name: t6
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SERVER_ID=10
      - AREA_CODE=HO_NKKN_TANG_6


  t7:
    <<: *deepstream-service
    container_name: t7
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SERVER_ID=10
      - AREA_CODE=HO_NKKN_TANG_7


  t8:
    <<: *deepstream-service
    container_name: t8
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SERVER_ID=10
      - AREA_CODE=HO_NKKN_TANG_8

  t9:
    <<: *deepstream-service
    container_name: t9
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SERVER_ID=10
      - AREA_CODE=HO_NKKN_TANG_9


  t10:
    <<: *deepstream-service
    container_name: t10
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SERVER_ID=10
      - AREA_CODE=HO_NKKN_TANG_10


