model:
  min_confidence: 0.5
  max_confidence: 1.0
  class_id: [0]

tracker:
  tracker_width: 640
  tracker_height: 384
  gpu_id: 0
  ll_lib_file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
  ll_config_file: resources/ds/config_tracker_NvDCF_perf.yml

reconnect:
  interval: 5
  attempts: 5
  drop_on_latency: true
  readd_delay: 5

streammux:
  width: 1920
  height: 1080
  batch_size: 4
  batched_push_timeout: 25000
  config_file_path: resources/ds/pgie_config.txt
